### ISSUE TITLE
wither_skeleton beheadings do not give behead points

### ISSUE THREAD

**Issue by EvModder** [crashdemons/LoreKillCounter#13]
Wither skeletons dropping a skull is not counted in the `Mobs Beheaded` stat.
This bug is probably due to PH API considering wither skeleton behead events separately from mob behead events.

This could either be resolved on PH's end, or here in the PH integration with a separate event listener.

Edit: I would attach a `bug` label if I could, but it appears I don't have permission to

**Comment by crashdemons** [comment]
Are you using PH for this, or just sending the PH event?
If you are using PH, can you provide your config?

I'm going to need a little more information about the situation too - so I'll give some context:

PlayerHeads should generate a Behead event if PlayerHeads itself drops the witherskeleton head/skull.
However, when a head drop has a vanilla cause, PH will not send an event with a few exceptions:
 - the relevant _behavior_ setting is set to _ignore_/_replace_ and PH generated its own head. (event for its own headdrop)
 - the behavior is set to _block_ (the head drop is cancelled full stop and no new event is sent)

It will be important whether this is a vanilla drop event or a PH drop (the item type doesn't necessarily matter, just the behavior and the situation that caused the drop).   If it's a vanilla one that's not replaced, I don't think I would send the same event for it, but I definitely could send a similar *type* of event just for purposes like this plugin.

If we're talking about fully-vanilla head drops, then I can confirm this will be a shortcoming of LoreKillCounter (only checking PH events) and not helped by PH (by not wrapping vanilla events).   I can temporarily patch LKC to check for vanilla headdrops (badly) but I would expect this to be phased out when PH adds support for vanilla behead events.

**Comment by crashdemons** [comment]
Here are development versions that should support vanilla head drop events/counting:
https://ci.meme.tips/job/PlayerHeads-5.x/1125/ (possibly very unstable due to large rework needed)
https://ci.meme.tips/job/LoreKillCounter/43/ (will not work on older builds than 5.2.14 build #1121)

These have not been tested yet to be stable, there was a lot of heavy changes needed to PH Core to support collecting event information and performing actions after collection rather than returning early.

I would not be surprised if there are any exceptions / odd behavior until it is more polished.

**Comment by EvModder** [comment]
Sorry for not clarifying; as you guessed, I meant head drops from a vanilla cause.
Therefore there is no bug, just the enhancement as identified in https://github.com/crashdemons/PlayerHeads/issues/73

(Marking as fixed)
